### ISSUE TITLE
bug in copyright year

### ISSUE THREAD

**Issue by tunnckoCore** [verbose/verb-generate-readme#17]
it's 2017 now, haha. And because I just updated one package that is from 2015 I set `start` year of the copyright helper to 2015 and it outpus

```md
Copyright © 2015, 2017, Charlike Mike Reagent. Released under the MIT license.
```

when the year is set to 2016 in `start` option it is correct (with dash)

```md
Copyright © 2016-2017, Charlike Mike Reagent. Released under the MIT license.
```

So I believe it should be

```md
Copyright © 2015-2017, Charlike Mike Reagent. Released under the MIT license.
```

when

```md
## License
{%= copyright({ start: 2015, linkify: true, prefix: 'Copyright', symbol: '©' }) %} {%= license %}
```

**Comment by tunnckoCore** [comment]
It's more [update-copyright](https://github.com/jonschlinkert/update-copyright) or [helper-copyright](https://github.com/helpers/helper-copyright), but don't know where.

Also tried with `options.first` and `options.years: '2015-2017'` and not helps.

**Comment by jonschlinkert** [comment]
actually, it's correct. If we want to follow copyright law to the letter, you're not supposed to update the copyright year during the year in which the code was modified. So if the last year that the copyright was modified is 2015, then the correct date format is `2015, 2017`.

**Comment by tunnckoCore** [comment]
Don't know. It's strange to me. If `2016-2017` is correct, then it make sense `2015-2017` to be correct too, because it looks (and should means) like _"oh okey, all years from 2015 - 2015, 2016 and current'_, but if it is 2015, 2017 it looks more like _"wait, what about 2016?"_.

But anyway, don't really care about these licenses so much. It just look strange to me.

**Comment by jonschlinkert** [comment]
> Don't know. It's strange to me.

This isn't my opinion, it's the law.

**Comment by tunnckoCore** [comment]
Yea okey :D
