### ISSUE TITLE
license in the footer isn't linkable

### ISSUE THREAD

**Issue by tunnckoCore** [verbose/verb-generate-readme#20]
![2017-02-28-15 25 09_740x215_scrot](https://cloud.githubusercontent.com/assets/5038030/23406819/9baec446-fdc9-11e6-942f-d46100ff3b45.png)

just noticed that, not sure from which day is, but i believe it is from recent update to `0.4.2`. Also seen that you updated few libs last few days and you don't have that problem. Ideas? I didn't change anything

It seems, that it happend around 20 feb? I believe my last readme update using `0.4.1` is from 20 feb.

markdown isn't changed from that in last months

```md
## License
{%= copyright({ start: 2016, linkify: true, prefix: 'Copyright', symbol: '©' }) %} {%= license %}

```

**Comment by jonschlinkert** [comment]
Hmm, maybe I fixed that locally and forgot to push it up... I'll check today, thanks for the issue
