### ISSUE TITLE
Keep asking me for adding a .verb.md

### ISSUE THREAD

**Issue by olstenlarck** [verbose/verb-generate-readme#22]
Heya there! :taco: 

Last night pre-installed my ArchLinux box and now when i installed fresh copies of `verbose/verb#dev` and `verb-generate-readme` and ran it i got always asking for that do i want to create `.verb.md` file, while i have one.

![2017-10-23-23 37 43_1280x1024_scrot](https://user-images.githubusercontent.com/5038030/31912116-92cdb070-b84b-11e7-8eeb-00778d14660f.png)

**Comment by olstenlarck** [comment]
Ohh... doh. Sorry, my fault. I was in the upper folder!

**Comment by jonschlinkert** [comment]
No worries lol, I've done the same thing many, many times lol.
