### ISSUE TITLE
Usage with scoped packages?

### ISSUE THREAD

**Issue by phun-ky** [verbose/verb-generate-readme#24]
I have a package named: `@scope/core`, and when generating the readme, the name of the package in the readme file becomes: `scope`, not `core` or `@scope/core`. How can I get the correct package name in the readme?

**Comment by tunnckoCore** [comment]
are you using so-called verb#dev? readme here still mentions only `npm install verb` which is pretty old. try installing `verbose/verb#dev` instead.

I dont think the `name` is handled differently, so you should get it directly from the pkg json as it is there.

**Comment by phun-ky** [comment]
I'm using `verbose/verb#dev`

**Comment by phun-ky** [comment]
My `package.json`:

    {
      "name": "@guybrusssh/color",
    }

My `.verb.md`:

    # {%= name %} v{%= version %}

My generated `README.md`:

    # guybrusssh v0.0.0

**Comment by phun-ky** [comment]
Could it be that `verb-repo-data` or `generate-data` is actually escaping `@` and `/` ?

**Comment by tunnckoCore** [comment]
Ookey, thanks. So we should track it down to somewhere in the deps. I cant remember where the populating is done, but checked verb-data, generate-data and few more places and didnt find anything specific for the `name`.. hm.

**Comment by tunnckoCore** [comment]
neither of them, I checked. probably in verb-repo-helpers

edit: haha, nope.

**Comment by doowb** [comment]
@phun-ky and @olstenlarck I had this issue and I thought that I fixed it. I might not have merged a PR or published the change though. I'll take a look and get it published. It had to do with how the `name` and `alias` were normalized.

**Comment by doowb** [comment]
@phun-ky I published a patch of a dependency where this is fixed. You'll have to make sure to uninstall and re-install `verb-generate-readme` to get the latest dependencies.

`{%= name %}` in the templates should have the scope on them now. If you need to update your "usage" section (if that's still in your `.verb.md`), then use `varname` instead of name:

````markdown
## Usage

```js
var {%= varname %} = require('{%= name %}');
```
````

**Comment by phun-ky** [comment]
@doowb where did you publish that patch? I can't find reference of it in this in your code. I've uninstalled and installed `verb-generate-readme` with no luck:

    $ npm uninstall -g verb-generate-readme && npm cache clean --force && npm install -g verb-generate-readme
    $ + verb-generate-readme@0.7.0

`varname` and `name` are still: `guybrusssh`
