### ISSUE TITLE
How to set data

### ISSUE THREAD

**Issue by stefanwalther** [verbose/verb-generate-readme#8]
Hi,

how can I set custom config for e.g. `twitter.username`, I tried:

```js
"verb": {
    "run": true,
    "toc": false,
    "data": {
      "twitter": {"username": "waltherstefan"}
    },
...
````
But this is not working as expected ...

Regards
Stefan

**Comment by jonschlinkert** [comment]
It might just be `"twitter": "waltherstefan"`, the rest of it looks correct

**Comment by jonschlinkert** [comment]
@stefanwalther btw, you were wondering about "the big picture", [this might help](https://github.com/node-toolkit/getting-started#suite). I'd still like to get together, I replied on gitter but I don't see those messages sometimes, so you probably didn't either. 

if you check my profile my email address is there if you want to contact me directly so we can plan a day/time. thanks

**Comment by stefanwalther** [comment]
This is absolutely great, I will spend some time next week on that ;-)
Very much looking forward to seeing everything working ...

**Comment by stefanwalther** [comment]
This is a game-changer for nodejs devs ...

**Comment by jonschlinkert** [comment]
thanks! we think so too! game-changer was the goal :)

> Very much looking forward to seeing everything working ..

I've been struggling with getting all of the pieces documented, but now that I can describe how everything fits together, hopefully others will be able to help with it. 

fwiw, most bugs or issues we experience at this point should be relatively minor, and will be eliminated through feedback and usage. the "hard part" is over :)

**Comment by stefanwalther** [comment]
> hopefully others will be able to help with it

Count on me ...

> most bugs or issues we experience at this point should be relatively minor

Couldn't get generate to work at all, non of the libs and generators, tested several node.js versions, none of them with success, but beside that:

- assemble is really stable in the meanwhile
- the same applies for verb

So really great, just looking forward to get a bit more insight to leverage the full power of all these tools.
Again, just great!

**Comment by jonschlinkert** [comment]
> Couldn't get generate to work at all, non of the libs and generators, tested several node.js versions, none of them with success, but beside that:

Which generators? I completely reinstall generate and generators several times a day with no issues. Maybe there is something we're not explaining in the docs? 

Can you try this, just to see if it works?

```sh
$ npm install --global generate generate-license
```

then run:

```sh
$ gen license
```

I also have some changes to push up. I'll try to do that in a bit

**Comment by jonschlinkert** [comment]
> the same applies for verb

Oh good, have you been using the dev branch?

**Comment by stefanwalther** [comment]
reg verb: Yes, using the dev branch.

**Comment by jonschlinkert** [comment]
verb uses generate. if verb is working for you, I'm not sure why generate isn't working. verb-readme-generator is just a generate generator

**Comment by stefanwalther** [comment]
hmmm ;-)

**Comment by stefanwalther** [comment]
BTW, now works all like a glance ;-)

**Comment by jonschlinkert** [comment]
> now works all like a glance ;-)

that's great! I'm going to merge verb into master as soon as I can get some docs finished for the readme.

**Comment by stefanwalther** [comment]
;-) Sorry, this drives me crazy, twitter customization is again not working and I cannot find it, still using `"twitter": "waltherstefan"` in the verb section of package.json, but not it does not work anymore. Any ideas?

**Comment by jonschlinkert** [comment]
Yeah it's driving me crazy too. The template is `{%= author.twitter %}`.

**Comment by jonschlinkert** [comment]
you can do a pr to `verb-repo-data` to normalize `twitter` onto `author.twitter` or something.

**Comment by stefanwalther** [comment]
OK, thx - will do. Just to get rid of this ;-)

**Comment by jonschlinkert** [comment]
> Just to get rid of this ;-)

yeah, try to remember that you're using unreleased software. Verb 0.9.0 is in beta. You recently commented that assemble has been stable - that's because we released it when it was stable. Verb isn't. So these issues are probably more frustrating for me than you lol. I'm really excited and happy that you want to use the dev branch and provide helpful feedback, but it's time consuming to keep up with issues for something we haven't even released. 

I don't think there is a "perfect scenario", we both just need to be fair minded about it and realize that we have to make compromises
